# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - script: exit 1
    # condition: and(true, false)

  - job: A2
    dependsOn: A1
    steps:
    - script: echo "job B"
    condition: and(true, false)
    
- stage: B
  jobs:
  - job: B1
    steps:
    - script: echo "Stage B job B1"